name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Convert repository owner to lowercase
      id: lowercase_owner
      run: echo "owner=${{ github.repository_owner | toLowerCase }}" >> $GITHUB_ENV

    - name: Log in to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner}}
        password: ${{ secrets.GITHUB_TOKEN}}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v5
      with: 
        context: .
        push : true
        tags: |
          ghcr.io/${{ env.owner }}/esraagaber/getting-started:latest
          ghcr.io/${{ env.owner }}/esraagaber/getting-started:${{ github.sha }}
